# Generated by Django 4.2.18 on 2025-01-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC_App', '0002_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
