# Generated by Django 4.2.18 on 2025-01-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC_App', '0003_train_booked_seats_train_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='train',
            name='total_seats',
        ),
    ]
