# Generated by Django 4.2.18 on 2025-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC_App', '0004_remove_train_booked_seats_remove_train_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
